<?php

namespace App\Strategy;

use Carbon\CarbonImmutable;

/**
 * Immutable representation of a trading signal generated by a strategy.
 *
 * This is a pure data contract for the Strategy Engine: it carries the
 * decision, its reason, and when it was generated. It has no knowledge
 * of price, risk, execution, or persistence.
 */
final readonly class Signal
{
    public function __construct(
        public SignalType $type,
        public string $reason,
        public CarbonImmutable $generatedAt,
    ) {}
}
